fl <- read.table("FlixIt (1).dat",header=TRUE)
agepart <- glm(Partic~Age,data=fl,family ="binomial")
summary(agepart)
fl["region"]<-as.factor(fl$Region)
repart <- glm(Partic~region,data=fl,family ="binomial")
summary(repart)
nullmodel<- glm(Partic~1,data=fl,family ="binomial")
full<- glm(Partic~Age+region,data=fl,family ="binomial")
summary(full)
anova(nullmodel,agepart,test="LRT")
anova(nullmodel,repart,test="LRT")
anova(agepart,full,test="LRT")
anova(repart,full,test="LRT")
library(pscl)
pR2(full)
fl["pp"]<-predict(full,list(Age=fl$Age,region=fl$region),type="response")
library(SDMTools)
fl["pb"]<-(fl$pp>0.5)+0
confusion <- t(confusion.matrix(fl$Partic,fl$pb))
confusion<-addmargins(confusion)
confusion
library(pROC)
ROC=roc(Partic~Age,data=fl)
plot(ROC,col="red")
p<-exp(-20.31823+17.74620+0.05545*35)/(1+exp(-20.31823+17.74620+0.05545*35))
odds<-p/(1-p)
p
odds
library(agricolae)
correlation(fl$Age,fl$region,method="pearson")

data<- read.table('KII.dat',header=TRUE)
data$jobtype <- as.factor(data$JobType)
linear <- lm(Commitment~Tenure,data=data)
summary(linear)
linear2<-lm(Commitment~Tenure+jobtype,data=data)
summary(linear2)
total <- lm(Commitment~Tenure+jobtype+Tenure*jobtype,data=data)
summary(total)
(0.24816+(0.24816-0.49939))/2
library(heplots)
etasq(total,data=data,anova=TRUE,partial=FALSE)
mn <- mean(data$Tenure)
predict(total,data.frame(jobtype='1',Tenure=9))-predict(total,data.frame(jobtype='2',Tenure=9))
predict(total,data.frame(jobtype='1',Tenure=5))-predict(total,data.frame(jobtype='2',Tenure=6))


data<-read.table("AAA.dat",header=TRUE)
lm<-lm(Demand~Price,data=data)
summary(lm)
data$lndemand<-log(data$Demand)
loglin <- lm(lndemand~Price,data=data)
summary(loglin)
data$lnprice <- log(data$Price)
loglog<-lm(lndemand~lnprice,data=data)
summary(loglog)
predictlin <- predict(lm,data.frame(Price=3))
lnpredictloglin<-(predict(loglin,data.frame(Price=3)))
predictloglin<-exp(lnpredictloglin)
predictloglog<-exp(predict(loglog,data.frame(lnprice=log(3))))
c(predictlin,predictloglin,predictloglog)

library(astsa)
data<-read.table("DCTrafficSignal.dat",header=TRUE)
head(data)
x.lm<-lm(BulbReplacements~Month,data=data)
summary(x.lm)
predictlm <- predict(x.lm,data.frame(Month=241))
data<-ts(data[,2])
plot(data,type='b')
datalag1<-lag(data,-1)
new<-cbind(data,datalag1)
head(new)
ar1fit<-lm(data~datalag1,data=new)
summary(ar1fit)
predictar <- predict(ar1fit,data.frame(datalag1=new[241,2]))
lag1.plot(data,1)
acf(data,datalim=c(1,19))
pacf(data)
